services:
  snc-evaluation-ui:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      NODE_ENV: production

      # Nitro
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: ${PORT}

      # Application
      BASE_URL: ${BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    ports:
      - "${PORT}:${PORT}"

    healthcheck:
      disable: true